apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-dnsserver-pvc
  namespace: technitium
  labels:
    app.kubernetes.io/name: technitium-dnsserver
    app.kubernetes.io/version: "15.1.0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi