apiVersion: v1
kind: ServiceAccount
metadata:
  name: technitium-service-account
  namespace: technitium
  labels:
    app.kubernetes.io/name: technitium-dnsserver
    app.kubernetes.io/version: "15.1.0"
automountServiceAccountToken: false