apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelog-pvc
  namespace: lubelog
  labels:
    app.kubernetes.io/name: lubelog
    app.kubernetes.io/version: "1.6.1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi