apiVersion: v1
kind: ServiceAccount
metadata:
  name: lubelog-service-account
  namespace: lubelog
  labels:
    app.kubernetes.io/name: lubelog
    app.kubernetes.io/version: "1.6.3"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lubelog-postgres-service-account
  namespace: lubelog
  labels:
    app.kubernetes.io/name: lubelog-postgres
    app.kubernetes.io/version: "1.6.3"
automountServiceAccountToken: false