---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto-passwd
  namespace: mosquitto
spec:
  encryptedData:
    passwd: AgC1TOPN07Gm11/8yumfuVGL4tn5BoRB06ZVfjCsHZzleyz6mVjgtxQiMiofP5fb7srxoDt4SUIvLLIMr0iWFVZ/+mUUCctamGz0jyC7qaSaMJ2oTVe70uWpTYJM6A/pSBrMhm5knzO1dTkVdTjLap6jGtTFQxBJSbnL+vKxLHwdU12yP5OSRqgTmf6JGHSpeo3cE6KavPA+/8Y1d7IDECW+2hln3L914jAOVyLAaBLc6BBQa+BoW59DPq98OqUbgMJdMnNByI2HdLKQX3nNASHtRtRg0nAS0sz5WnDXh7Z+4ezZnGxOkIoaprLDwPdJh6nACgW5dDSF4Htmpq1KebvX7Dzm4PvK+X18sLJH0Mns2G8/n3E2z09tRYF6itpYDVCU0h66WfFXG3sQMnBGCf3reCR+kIWxbhmBCe9KVgplP9wHJA8YCvifdzItbF0yrbJqVz0LNGUpnKwYUKwtfP5oZzzZhl8h7JMlItkxC8z7f9zOvScgDKFmkoq5p9RmB8x3YOm68x2eFVxP2wBlTU8GQbkWfqHfQNVoLT9zMr7GC2ZPvrWolEKOPRR113uaz28bBspEohLX3GWQ/3hu4GHRKfYP5nRGxjYKUC2SbEIdlCAqe6m9ys36G5KboImEwHbfgrntMlYjnuUWaJNQFaTPneHBknXIyoN+cHzwNLS4T2fu7WloaL7Anj4XichGMB8LFLSrdMn/yhuNwCU9ykJj/ioG0wWdl6Jzf9MsnEWBmET54XlyKjAz+I9qgUZM8RGoRnzRqEYLhdg8FiuBB8Ez6M8vd7OHbCCIXmNRiNM/wI9PBKIEC2xkPA+bjWGoloCOz506MVXP3n3b9btJRzAIWdtw6zhH3Gv/
  template:
    metadata:
      name: mosquitto-passwd
      namespace: mosquitto
