---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto-passwd
  namespace: mosquitto
spec:
  encryptedData:
    passwd: AgDZ8h5DOOTW1QBXU5vzpRbo2oniyymeDiGwOjf0RFND2s5sZey15RBVGVU3Sxb30mhG6Q8bJUDAaNsjgzngjilubXopLornjrb/sZ83Q9Isr9FE3lvU+xkXfGb7FZcFIQHsrNfklp2f9L5/TCH15OKz0dlVgRoCE1JUzbQCV5K4Bx51H5jsnvIE2u3EJglU1xl37E95NjlD8dfOo8YS/C0nyjVdjLOULWEo1M6OhrIml+T9jDEJNM9t6fs50k6nLSGeRUat2Z4+k5+cqMwiSyxfXEOFfl+HmA6OjsRgsGYMmqQrTfI3c5SjCmSUrqdQJ9w/pOLAZ8tychRe9kmm8e6O3wrLutj2d92HdOSbASfWtB2aQQp9nJQRKyN2g3JXiGzrV07G3MqsE7RWNO+iw72JufMMKyQqRzoHzeJtw7BTN9nPsW/ASm9akXFw5nOH798oR1j6BSlS+/BpkyN3ZMAqwqZf5eAwRMScghwKoMVzXhXjx4HGIDe1F5F/RKeLaKqemEg1Qaw0phnYLilYB/ebj1lFUrpmck6R+csKeUQ8+faJlfvD0/qAkOjqb8SVOXiaU79d8DduvGXeJbLiDKHKufxtmlVrCs8nv6KyOyk+9iWNlsyxWPIT4Rdd1Y77UfmI3mYKtEzWKBwRgLWwXOD10l5PeY2uj4HyIaROLBk+4PqTsSihYhhB3JzJGXHgjjTZiM0o9iTwm3ZYu702ZY4SFo/ynsm45X5kpOO9sKRRoFLSm6jTSSO7WIaLvNNLyNHmgDm2vzLyWz+7dTmiNvpAZVR5iuii0XMHGogRMsHLfhs7s/iXM/Jk401RiirMKBucdDu1iGbmX+/uQVnF4WbU+p0F6Clo22sf
  template:
    metadata:
      name: mosquitto-passwd
      namespace: mosquitto
