kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/version: "2026.3.1"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "longhorn"
  resources:
    requests:
      storage: "5Gi"