apiVersion: v1
kind: ServiceAccount
metadata:
  name: hass-service-account
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/version: "2026.4.4"
automountServiceAccountToken: false