apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diun-data
  namespace: diun
  labels:
    app.kubernetes.io/name: diun
    app.kubernetes.io/version: "4.31.0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi