---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: diun-secret
  namespace: diun
spec:
  encryptedData:
    DIUN_NOTIF_TELEGRAM_CHATIDS: AgDFv9+uU2doJDYHNQgZQbVqzFe/pkgbWXNWzIFNPaI25NYYa5Wh+4TvQyraU4N3IJydyHxsYUqVv2/AsKmmY7s71PsQ1FncMqN06dDRt9tw5i6bFY9tnAprf+eC1HPALV802BsOQpGbhRpf1lXzlqZuMDCr6EubPHxxwOTMTbstqfKWZwsT0IdBX6f0j7U3HuAiuQEJp5M6LMsx/TRjJbJFftNLyyeLOz3GSgbfBUhBWIYH+B5E+HPTvaIYtl62+B3VA3o2N5v7sMAgzq7GQ0FboIobjPQuCbF3sIxIlWWt+02+YHdki0QVXPW5t34b5fiJcTmaR1dp8fVOZ1cRfU4tyDahPAJ2yF5KvqQkKzD2M6pNsfHhlHFwmbekBvL3jHNfL2OD/o1OcsnCPJOARXU7phuEopzD03NUVYrpaEHnmVwbST31X+I7O49ebnk7vGBOPCZ0DlV7D/++JsmpmHpg4BTJr0WKWaRiGxVfN9RTYYPG3ZX+6sHY3U25XivVnd81zClQ8xaebVaqNf1djrKOrT1Q2SMg9pWXM48f2xYGOKqE4nVYJVPeBUe8Ebv8xOj79ukUuNL9qemBO6Ts7Pu1HEAP0Mf6WHJLGhG7Z4gV/hhNRaLH7j2pkbqkiRgXckWVU1B4yWaBaqtRdk/ORQUH4fku2oTBdvkg5hF26ZZNX3uDBqQCiNbechY1pwvAE2tLSE4eTPmB4pGG
    DIUN_NOTIF_TELEGRAM_TOKEN: AgBTJZJqxnTb+RyCwDgrXLkbQ+6vaGXFbwv79mCyYQoD48vV7MWRUslFJ7jb+LIN74hSHqKwpH8WIIlOHbxqvHsmD2yiq1DIPZDzFKZn1dH1uT2BGaMP0TgjVjl7GFqDX1jdfStLYuyoR0Sp38H/IdHd620oMRGVebsld0gFNJ3EA6UCpMpsVBicL7MmGoYa4jcpUCInTdw18at6BHNcU4Jgh58sV2Z9wqoG3+cAas4g3/S3DSWgs4Zox3XVqP4Td3AtaeC8FdAHbbYvei3ZtjXqESzomN2lQmgNVq6DbHa7X4vJKlFIMO++E3lS1LgMrAXckciHTaESaCypMB7XBCW4t0qWdqHYArSx8FfeN+FR7UgaBvf9odbrN+dFKMLmyAv6w6+yo6eR9Q6XEkJC92PdJ2s0ZpVM5TUoTaNS68mBRF9/QfpgQD3vN4jdFS6IuFOm1D/u6NHf1wMLT0kpaQBLz8FRb72hX9Y3Ap2UgbyyHipuRlPjt9zEZHoVG5iFD3ZKrUmPZL9rN1EWOfYp7Epyp5nEzUO64rW2QAqmZeKrXTOkUeYH/VNUt3/vWidT6fN0sUbaeWzD/CazZCZ5Lc3Qh7t/zw7NQhFS02TUadOarp39OQMD+0RuKI3+ylg6NkVtRVQ2TAFwbGAx9H+BPSzUnd3jxmpSzh/vkqmmjrSNfke5CmAdRJ2bBBnvpLXNZXwKHqKw4zAtCar0gZd3M03BqqK9fqXqkCH5d+LfiUBK84WgUaCHtTvRJYf/nj0S
  template:
    metadata:
      name: diun-secret
      namespace: diun
