apiVersion: v1
kind: ServiceAccount
metadata:
  name: diun
  namespace: diun
  labels:
    app.kubernetes.io/name: diun
    app.kubernetes.io/version: "4.31.0"
automountServiceAccountToken: false