apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
  namespace: esphome
  labels:
    app.kubernetes.io/name: esphome
    app.kubernetes.io/version: "2026.4.0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi