apiVersion: v1
kind: ServiceAccount
metadata:
  name: esphome
  namespace: esphome
  labels:
    app.kubernetes.io/name: esphome
    app.kubernetes.io/version: "2026.4.0"
automountServiceAccountToken: false