---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zigbee2mqtt-mqtt-secret
  namespace: zigbee2mqtt
spec:
  encryptedData:
    mqtt-password: AgCJJZc+YmU26PfvTFBhU0mkZek1Mdq6ZbMlJZj7+vxhh13eRt/kaGdF8CQ4nahSmZciuCNfxbwvlEdQ1fLWrxyMg9vHrVNtMlQsIkWWZaxBxBOGyvoITEifBPsbzVGLGKX+Jpk8CaMhW7fNbd5bi3qn5ZQgAhd+bnX4+h22sCCEfeWTq5HdxDOWLVZBpHRJ9dSlXyeqgrWvvnqJ43eRWGk/JinBNgN8obfAU2spgXYt7jIWsUEmVkBLcVGOnkiR5Tj9vIvszOImjMTLZjfmdVgSCyvr+f8PB+9yT3rWin6X68i6nvb/YlYjvlA+p6SyPtOxWeOQjomnxNHV/+jMG+hZElifSaOKz2LPRuNk2t2i+NDdfOyxeQUDH3F2+Co0U5SWC57CttcX+NYDr/Eh5azsTcXiwUnCCMykGY/GgXOBCNe0fmzKSUqnOvjLIcPP3EWffv/B5FJ+grBPTOm10gWIQFIfWouC9GhJ9dwpqkUNNHsnVFbam75XYKSpx+BN6B6iOGcuGGp2xQRBOXyWlU+XrYibYcbqMqW/vUaJGRkkh0hfY/Qb1ct+EdeHmqCC6u1UEiCGg4jNRRdO7HmdxwpZja0vWY6+RMB7IdocmoVSBxoIMQrS5RG7AGwpGy6XMs1YGwsjjpXU0vG8+bOQJ0QSR+YnBAmdZb6X06uMiH1YO3kJjFpqKLYFrXs/PNGe2dZYTC64cJbPaViv4Y6/FlQKvyU7AC/leFCe28BHLgdeUA==
  template:
    metadata:
      name: zigbee2mqtt-mqtt-secret
      namespace: zigbee2mqtt
