apiVersion: v1
kind: ServiceAccount
metadata:
  name: zigbee2mqtt-service-account
  namespace: zigbee2mqtt
  labels:
    app.kubernetes.io/name: zigbee2mqtt
    app.kubernetes.io/version: "2.9.2"
automountServiceAccountToken: false