---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAL73Y1JDJnnsyW6St+tPOBQ2L47LKUFOohVp89WvSa9i2hXqZ4ZE8dIHdjrdFpkpzFuFNBHtYp9gkcFu95U5lj2rjKRFK1q2YMckT6NZpxY4KjjlfHP/Ds0S2JfZvioR20WSe2qw9wT4KIfKD84w1jpnwbqxDoUwNEo6WMz5AiGeGu300ia07sNkwDHI8d6ZpcLH6ZkDUwnN0fkIWxzGhPmMQasHUFWugNbMVAanunJNTt3acJR9A2Q2EwmxYA641n7mRriAhE9jajOPVYvdjIMChxNlQCw/8EZ9zc1ehLwagOPZTyg/z8ZlPzHruogz7lPesxwbFjuahekV5rRBzPLquFQ8wGyQA48oDcO27oIZmW+FoxFEDkXCxhhSdI8wZk1Tk+cHlB6fW7vbP1HgBZaRlt9nnEraDScEs5sX1pQb2dzL+or5jf5xr+rOwaci08mJDPGzUIF70P1i+dP+duO2rkEvfHTz1woaQCDg1BVN26MGdFYvKiMiIuj6EMB8lOlAD+CPZNVLK5GjSgE3AjMcfl/2xiDzWOb4RMKRso4NG5O7ALzLmuLx9K0vnzIlVHoDf/hsw2kyjR9rlmxGLYdplz8HvazRCvq2yM7Yp4WLYJDghl2FwmJNp39YOCH/uOMbRPr5tIXEnmwO/xPl2x9pf78j6KjgmMqOp3oXwOA2/SYrTCd7LSW1G9YT9/Va5Atj2BKAyza5ig2FEmh0E2Y+gBxDJjolzYoVKcOQhJOi3N6o2+jAre
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
